name: Python trial

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.11", "3.13", "pypy3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

 
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      
      - name: Test with pytest
        run: |
          # Install pytest and the coverage tool.
          pip install pytest pytest-cov
          # Run the tests and generate a Junit and coverage reports.
          pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      
      - name: Install Ruff
        run: pip install ruff

      
      - name: Lint code with Ruff
        run: ruff check --output-format=github --target-version=py39
       

     
      - name: Check code formatting with Ruff
        run: ruff format --diff --target-version=py39
        continue-on-error: true
