name: Python trial

on: [push]

jobs:
  build:
     runs-on: ubuntu-latest

     steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      
      # - name: Test with pytest
      #   run: |
      #     # Install pytest and the coverage tool.
      #     pip install pytest pytest-cov
      #     # Run the tests and generate a Junit and coverage reports.
      #     pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      
      - name: Install pylint
        run: pip install pylint

      
      - name: Lint code with pylint
        run: pylint check --output-format=github --target-version=py39
       

     
      - name: Check code formatting with pylint
        run: pylint format --diff --target-version=py39
        continue-on-error: true
