name: python trial

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


  lint:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Linters (pylint, flake8)
        run: |
          pip install pylint
          pip install flake8
      
      - name: Run flake8
        run: flake8 . --count --max-complexity=10 --max-line-length=88 --statistics

      - name: Run pylint
        run: pylint --output-format=github .

  test:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies and pytest
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate build step
        run: echo "Simulating build step - package or zip your app here"
